#ifndef OXC_BRIDGE_H
#define OXC_BRIDGE_H

/* Auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Result struct returned across FFI boundary.
 */
typedef struct OxcTransformResult {
  /**
   * Transformed JavaScript (caller must free with oxc_free_string)
   */
  char *javascript;
  /**
   * Error message if transform failed, null on success (caller must free)
   */
  char *error;
} OxcTransformResult;

/**
 * Transform TypeScript/TSX source to JavaScript.
 *
 * # Safety
 * `source` and `filename` must be valid null-terminated UTF-8 C strings.
 */
struct OxcTransformResult oxc_transform(const char *source, const char *filename);

/**
 * Free a string returned by oxc_transform.
 *
 * # Safety
 * `ptr` must have been returned by oxc_transform, or be null.
 */
void oxc_free_string(char *ptr);

#endif  /* OXC_BRIDGE_H */
